//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEFP1Av4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Inventario
    {
        public int idProducto { get; set; }
        public int SKU { get; set; }
        public string Producto { get; set; }
        public Nullable<int> PrecioCosto { get; set; }
        public Nullable<int> PrecioPublico { get; set; }
        public Nullable<int> PrecioMayorista { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> Almacen { get; set; }
    }
}
